#spring:
#  application:
#    name: APIGATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: BOOKING-MS
#          uri: lb://BOOKING-MS
#          predicates:
#            - Path=/book/**
#server:
#  port: 9006
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
